[workspace]
members = [
    "libp2p",
    "core",
    "misc/metrics",
    "misc/multistream-select",
    "misc/rw-stream-sink",
    "misc/keygen",
    "misc/prost-codec",
    "misc/quickcheck-ext",
    "muxers/mplex",
    "muxers/yamux",
    "protocols/dcutr",
    "protocols/autonat",
    "protocols/floodsub",
    "protocols/gossipsub",
    "protocols/rendezvous",
    "protocols/identify",
    "protocols/kad",
    "protocols/mdns",
    "protocols/ping",
    "protocols/relay",
    "protocols/request-response",
    "swarm",
    "swarm-derive",
    "transports/deflate",
    "transports/dns",
    "transports/noise",
    "transports/plaintext",
    "transports/pnet",
    "transports/tcp",
    "transports/uds",
    "transports/websocket",
    "transports/wasm-ext"
]
