[workspace]
members = [
    "libp2p",
    "libp2p-core",
    "libp2p-swarm",
    "libp2p-swarm-derive",
    "misc/keygen",
    "misc/libp2p-metrics",
    "misc/multistream-select",
    "misc/prost-codec",
    "misc/quickcheck-ext",
    "misc/rw-stream-sink",
    "muxers/libp2p-mplex",
    "muxers/libp2p-yamux",
    "muxers/test-harness",
    "protocols/libp2p-autonat",
    "protocols/libp2p-dcutr",
    "protocols/libp2p-floodsub",
    "protocols/libp2p-gossipsub",
    "protocols/libp2p-identify",
    "protocols/libp2p-kad",
    "protocols/libp2p-mdns",
    "protocols/libp2p-ping",
    "protocols/libp2p-relay",
    "protocols/libp2p-rendezvous",
    "protocols/libp2p-request-response",
    "transports/libp2p-deflate",
    "transports/libp2p-dns",
    "transports/libp2p-noise",
    "transports/libp2p-plaintext",
    "transports/libp2p-pnet",
    "transports/libp2p-tcp",
    "transports/libp2p-uds",
    "transports/libp2p-wasm-ext",
    "transports/libp2p-websocket",
]
