[package]
name = "libp2p-metrics"
edition = "2021"
rust-version = "1.65.0"
description = "Metrics for libp2p"
version = "0.12.0"
authors = ["Max Inden <mail@max-inden.de>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[features]
gossipsub = ["libp2p-gossipsub"]
identify = ["libp2p-identify"]
kad = ["libp2p-kad"]
ping = ["libp2p-ping"]
relay = ["libp2p-relay"]
dcutr = ["libp2p-dcutr"]

[dependencies]
libp2p-core = { workspace = true }
libp2p-dcutr =  { workspace = true, optional = true }
libp2p-identify = { workspace = true, optional = true }
libp2p-kad = { workspace = true, optional = true }
libp2p-ping = { workspace = true, optional = true }
libp2p-relay =  { workspace = true, optional = true }
libp2p-swarm = { workspace = true }
libp2p-identity = { workspace = true }
prometheus-client = "0.19.0"

[target.'cfg(not(target_os = "unknown"))'.dependencies]
libp2p-gossipsub =  { workspace = true, optional = true }

[dev-dependencies]
env_logger = "0.10.0"
futures = "0.3.28"
hyper = { version = "0.14", features = ["server", "tcp", "http1"] }
libp2p-noise = { workspace = true }
libp2p-ping = { workspace = true }
libp2p-swarm = { workspace = true, features = ["macros"] }
libp2p-tcp = { workspace = true, features = ["async-io"] }
libp2p-yamux = { workspace = true }
log = "0.4.0"
tokio = { version = "1", features = ["rt-multi-thread"] }

# Passing arguments to the docsrs builder in order to properly document cfg's.
# More information: https://docs.rs/about/builds#cross-compiling
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
rustc-args = ["--cfg", "docsrs"]

[[example]]
name = "metrics"
required-features = ["ping", "identify"]
